### ISSUE TITLE
The script verify.py needs an argument to pass environment variables to the job

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.bio.base#14]
gridtk jman has this feature. 
It is possible to set environment variables to the grid submission using the argument `--environment`.
Would be useful to have the same feature in the `verify.py` script.

A patch is on the way

**Comment by siebenkopf** [comment]
Thanks Tiago. I guess that your solution works fine,

I wonder if it would also possible to have these parameters inside the grid configuration file, to avoid adding yet another command line option. However, I have to admit that I have added more and more command line options lately :-)

**Comment by tiagofrepereira2012** [comment]
Indeed, the list of arguments is long :-)
Well, I will merge this one

Thanks
