### ISSUE TITLE
score fusion script

### ISSUE THREAD

**Issue by khoury** [bioidiap/bob.bio.base#2]
The fusion script is currently in bob.bio.spear.
I think it's wiser to put it here but please let me know if someone has different point of view.

**Comment by siebenkopf** [comment]
Agreed. If the script is generic and does not rely on features of ``bob.bio.spear`` it should go here.

Please assure that you have similar command line options (including the short cuts) as in https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/script/evaluate.py#L54
This makes the functionality easier usable. Also, a bit of code documentation might help.

If possible, you might make the ``eval`` files optional. Sometimes, no evaluation set is available, so we only fuse the scores of the ``dev`` set.

**Comment by khoury** [comment]
Agreed. Will do so!
Thanks

**Comment by khoury** [comment]
changes done and documentation updated.

**Comment by siebenkopf** [comment]
I am afraid that this line:
https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/script/fusion_llr.py#L79
will not work with the 5-column style (as we have 5 entries there, and not 4). I don't see, why you have the ``data_dev`` variable at all, you should be able to directly work with ``gen_data_dev``. (same for eval).

Cheers
Manuel

**Comment by khoury** [comment]
Agreed, now it's improved! 
Thanks, Elie
