### ISSUE TITLE
Tests are failing on Ubuntu 12.04

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.bio.base#22]
Unit tests are failing on Ubuntu 12.04 (https://gitlab.idiap.ch/biometric/bob.nightlies/builds/2968)
Basically the function `numpy.full` does not exists in numpy 1.6 (the default for the ubuntu 12.04). The function is available since numpy 1.8.

For example, I would suggest to replace the code
```
numpy.full((1,len(probes)), numpy.nan, numpy.float64)
```
to
```
numpy.ones((1,len(probes)), numpy.float64) * numpy.nan
```

**Comment by anjos** [comment]
@siebenkopf: Would you please fix those with the solution from Tiago? The tests continue to fail. Please push this fix into the nightlies.

**Comment by siebenkopf** [comment]
OK, fixed it. For the next time, feel free to correct these kind of small issues yourself -- if you are sure that the fix does not create any side-effects.
