### ISSUE TITLE
It should be possible to list only resources attached to a particular bob.bio.XYZ implementation

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.bio.base#25]
As of today, all installed resources are listed on the screen.

If a user, for example, is going to run face recognition experiments, but bob.bio.spear is installed on the environment, all resources with for both packages will be listed.

It would be nice to have a command-line option on `resources.py` to filter out stuff that you're not interested on. For example:

```sh
$ ./bin/resources.py -dt database --package=bob.bio.face
```

Would, in this case, list only the resources for the `bob.bio.face` package.

**Comment by siebenkopf** [comment]
That should be rather easy to implement. I will go for it.

**Comment by anjos** [comment]
Howdy, has this been released with Bob 2.3.x? Can we close it?

**Comment by 183amir** [comment]
Yes.
