### ISSUE TITLE
Evaluation.py script has no EPC curve

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.bio.base#8]
I just noticed that the `./evaluate.py` script has no option to plot the EPC.

Is there any special reason for that?
I know that this script works fine if we provide, as input, only `--dev-files` and to plot the EPC we need both (dev and eval). 
If this is the reason to not have it, I can just output a warning saying that (if you set the `--epc` with no `--eval-files`).

Anyways, I can implement it, no problem.

**Comment by siebenkopf** [comment]
Please go ahead and implement it. The EPC curve was just not yet implemented. Instead of a warning, please raise an exception.
